### ISSUE TITLE
Global usage

### ISSUE THREAD

**Issue by genevieve** [pivotal-cf/jhanda#4]
Can jhanda do what om is doing [here](https://github.com/pivotal-cf/om/blob/master/commands/help.go)? That way om wouldn't have to build a global help text, and neither would other users of jhanda.

**Comment by mcwumbly** [comment]
Sounds good to me!

**Comment by kcboyle** [comment]
@genevieve would you happen to know what other teams are using jhanda? (other than `om`?)

**Comment by genevieve** [comment]
I think just om. cc @ryanmoran
