### ISSUE TITLE
Idea: ability to tag commands and/or flags as "Experimental" or "Deprecated"

### ISSUE THREAD

**Issue by mcwumbly** [pivotal-cf/jhanda#5]
In `om`, we occasionally introduce commands that are not yet mature.  We have been noting these as `**Experimental**` in the command help to indicate that the "API" for these commands has not yet stabilized.  And as we plan to remove commands, we flag them as `**Deprecated**` in the help and add a warning to the output.

Perhaps jhanda could support these concepts natively to better support the lifecycle for features as they are introduced, stabilized and eventually deprecated and removed.

Flags that are marked as such could get special treatment in help output, and have a warning displayed on stderr when they are invoked.  Or perhaps they could even be hidden unless something is set on the environment.

Not a fully baked idea, but figured I'd throw it out here for discussion. 

I also have not researched prior art too deeply here yet, but did notice these just now after a quick Google search: 

- https://godoc.org/github.com/spf13/pflag#FlagSet.MarkDeprecated
- https://godoc.org/github.com/spf13/pflag#FlagSet.MarkHidden

Perhaps there are other examples out there in the wild that would help inform the design of these features if it seems valuable to add them to jhanda.

**Comment by genevieve** [comment]
What do you think about this being the way that flags can be marked as deprecated or experimental?

```
diff --git a/usage_test.go b/usage_test.go
index 30fe987..b6fc46b 100644
--- a/usage_test.go
+++ b/usage_test.go
@@ -12,15 +12,19 @@ import (
 var _ = Describe("Usage", func() {
        It("returns a formatted version of the flag set usage", func() {
                usage, err := jhanda.PrintUsage(struct {
-                       Second []string `short:"2" long:"second" required:"true" default:"true" description:"the second flag"`
-                       Third  string   `          long:"third"                  env:"THIRD"    description:"the third flag"`
-                       First  bool     `short:"1" long:"first"  required:"true"                description:"the first flag"`
+                       Second []string `short:"2" long:"second" required:"true"     default:"true" description:"the second flag"`
+                       Third  string   `          long:"third"                      env:"THIRD"    description:"the third flag"`
+                       First  bool     `short:"1" long:"first"  required:"true"                    description:"the first flag"`
+                       Fourth string   `          long:"fourth" experimental:"true"                description:"the fourth flag"`
+                       Fifth  bool     `          long:"fifth"  deprecated:"true"                  description:"the fifth flag"`
                }{})
                Expect(err).NotTo(HaveOccurred())
                Expect(usage).To(Equal(strings.TrimSpace(`
 --first, -1     bool (required)              the first flag
 --second, -2    string (required, variadic)  the second flag (default: true)
 --third, THIRD  string                       the third flag
+--fourth        string                       **EXPERIMENTAL** the fourth flag
+--fifth         bool                         **DEPRECATED** the fifth flag
 `)))
        })
```

Do you also prefer the `pflag` way of removing a deprecated command from usage instead of writing `**DEPRECATED**`?

**Comment by mcwumbly** [comment]
I like your proposal as is... fancier stuff could come later if we think it'd be helpful :)

**Comment by mcwumbly** [comment]
Wow! that was fast :)

Does PR#7 also work for commands or it that one just for flags? I think we have use cases for flagging flags _and_ commands as experimental or deprecated in `om`:

```
$om help
...
  config-template                 **EXPERIMENTAL** generates a config template for the product
  configure-authentication        configures Ops Manager with an internal userstore and admin user account
  configure-bosh                  **DEPRECATED** configures Ops Manager deployed bosh director
```

**Comment by genevieve** [comment]
Users of jhanda write the description/short-description for command using this struct: https://github.com/pivotal-cf/jhanda/blob/master/usage.go#L13-L17

We could add two fields to this struct that say `Deprecated bool` and `Experimental bool` and then alter their description/short-description. Or we continue to leave it up to users.
